[general]
start_url = "gemini://gemini.circumlunar.space/capcom"
max_width = 200

[colors]
h1 = "#005500"
h2 = "#006c00"
h3 = "#008300"
list = "#444555"
text = "#373b2e"
background = "#f2e5bc"
[colors.quote]
    foreground="#505643"
    background="#eaddb6"

[characters]
h1 = " "
h2 = "  "
h3 = "  "
list = "- "

[fonts]
[fonts.finger]
    family = "monospace"
    size = 11
[fonts.gemini.text]
    family = "serif"
    size = 11
[fonts.gemini.h1]
    family = "sans"
    size = 16
    style = "bold"
[fonts.gemini.h2]
    family = "monospace"
    size = 13
    style = "bold"
[fonts.gemini.h3]
    family = "monospace"
    size = 12
    style = "bold"
[fonts.gemini.list]
    family = "sans"
    size = 11
    style = "oblique"
[fonts.gemini.quote]
    family = "sans"
    size = 10
    style = "italic"
[fonts.gopher]
    family = "monospace"
    size = 11