[general]
start_url = "gemini://gem.ortie.org"
max_width = 200

[colors]
h1 = "#005500"
h2 = "#006c00"
h3 = "#008300"
list = "#444555"
text = "#373b2e"
background = "#f2e5bc"
[colors.quote]
    foreground="#505643"
    background="#eaddb6"

[characters]
h1 = "# "
h2 = "## "
h3 = "### "
list = "- "

[fonts]
[fonts.finger]
    family = "monospace"
    size = 13
[fonts.gemini.text]
    family = "serif"
    size = 13
[fonts.gemini.h1]
    family = "monospace"
    size = 20
    style = "normal"
[fonts.gemini.h2]
    family = "monospace"
    size = 18
    style = "normal"
[fonts.gemini.h3]
    family = "monospace"
    size = 16
    style = "normal"
[fonts.gemini.list]
    family = "sans"
    size = 13
    style = "oblique"
[fonts.gemini.quote]
    family = "serif"
    size = 13
    style = "italic"
[fonts.gopher]
    family = "monospace"
    size = 13