[General]
LoadColor=#475547
Name=OldSchoolDark

[Background]
Color=#475547
ImageFile=
Type=0

[Foreground]
Color=#475547
Margin=95
Opacity=100
Padding=10
Position=1
Rounding=10
RoundingDisabled=0
Width=1200

[ForegroundBlur]
Enabled=false
Radius=32

[ForegroundShadow]
Color=#59925e
Enabled=false
Offset=0
Radius=18

[Spacings]
IndentFirstLine=true
LineSpacing=135
ParagraphAbove=0
ParagraphBelow=10
TabWidth=58

[Text]
Color=#fcffed
Font="Zilla Slab Medium,20,-1,5,50,0,0,0,0,0"
Misspelled=#c99a23
